export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const keys = [
    process.env.GROQ_API_KEY_1,
    process.env.GROQ_API_KEY_2,
    process.env.GROQ_API_KEY_3,
    process.env.GROQ_API_KEY_4,
    process.env.GROQ_API_KEY_5,
  ].filter(Boolean);

  const ip =
  req.headers["x-forwarded-for"]?.split(",")[0] ||
  req.socket.remoteAddress;

  if (isRateLimited(ip)) {
    return res.status(429).json({ error: "Slow down a bit" });
  }

  if (keys.length === 0) {
    return res.status(500).json({ error: 'No GROQ_API_KEY_* keys set in environment variables' });
  }

  if (!globalThis.__groqKeyIndex) globalThis.__groqKeyIndex = 0;

  const apiKey = keys[globalThis.__groqKeyIndex];
  globalThis.__groqKeyIndex = (globalThis.__groqKeyIndex + 1) % keys.length;

  const { history, system } = req.body;

  if (!history || !Array.isArray(history)) {
    return res.status(400).json({ error: 'Invalid request' });
  }

  if (history.length > 60) {
    return res.status(429).json({
      error: 'Conversation too long — please refresh to start a new one.'
    });
  }

  const lastUserMsg = [...history]
    .reverse()
    .find(m => m.role === 'user')?.parts?.[0]?.text || '';

  const isDuckiee2 =
    lastUserMsg.toLowerCase().includes('duckiee2') ||
    lastUserMsg.toLowerCase().includes('infuse');

  if (isDuckiee2) {
    return res.status(200).json({
      reply: `
## Duckiee2

Duckiee2 is a Minecraft plugin and texture pack developer known for creating custom content for the Minecraft community.

He publishes his work on Modrinth and also shares tutorials and development content on YouTube.

### Links
- Modrinth: https://modrinth.com/user/Duckiee2  
- YouTube: https://www.youtube.com/duckiee2  

This is a profile-style response generated by NoteBuddy.
`
    });
  }

  const chatHistory = history.slice(-12);

  function needsFreshData(messages) {
    const text = JSON.stringify(messages).toLowerCase();

    return (
      text.includes("latest") ||
      text.includes("update") ||
      text.includes("version") ||
      text.includes("current") ||
      text.includes("2026") ||
      text.includes("minecraft") ||
      text.includes("news")
    );
  }

  async function getFreshContext(query) {
    if (!query) return null;

    const q = query.toLowerCase();

    if (q.includes("minecraft")) {
      return "Minecraft uses a 2026 versioning system (26.x series). Recent stable releases are in the 26.1+ line. Avoid outdated 1.20.x information.";
    }

    return null;
  }

  const messages = [
    {
      role: 'system',
      content: system || 'You are a helpful school assistant.'
    }
  ];

  if (needsFreshData(chatHistory)) {
    const fresh = await getFreshContext(lastUserMsg);

    if (fresh) {
      messages.push({
        role: 'system',
        content: `UP-TO-DATE CONTEXT (highest priority): ${fresh}`
      });
    }
  }

  messages.push(
    ...chatHistory.map(msg => ({
      role: msg.role === 'model' ? 'assistant' : 'user',
      content: msg.parts?.[0]?.text || msg.content || ''
    }))
  );

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant',
        messages,
        max_tokens: 512,
        temperature: 0.7
      })
    });

    if (response.status === 429) {
      return res.status(429).json({
        error: 'Too busy right now — try again in a few seconds.'
      });
    }

    if (!response.ok) {
      const err = await response.json();
      return res.status(response.status).json({
        error: err.error?.message || 'Groq API error'
      });
    }

    const data = await response.json();
    const reply = data.choices?.[0]?.message?.content || 'No response.';

    return res.status(200).json({ reply });

  } catch (err) {
    return res.status(500).json({
      error: 'Failed to reach Groq: ' + err.message
    });
  }
}
